export const errorConstants = {
    NOT_SUPPORTED: 'NOT_SUPPORTED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    NOT_READABLE: 'NOT_READABLE',
    NOT_FOUND: 'NOT_FOUND',
    DEFAULT_ERROR: 'DEFAULT_ERROR'
  };
